obstacle_range: 2.5
raytrace_range: 3.5
# the car is 53.4 cm x 29 cm
footprint: [[-0.27, -0.145], [-0.27, 0.145], [0.27, 0.145], [0.27, -0.145]]
inflation_radius: 0.5
transform_tolerance: 0.3
publish_frequency: 2

# Sometimes, its useful to be able to run navigation solely in the odometric frame. To do this, I find the easiest thing to do is to copy my local_costmap_params.yaml file over my global_costmap_params.yaml file and change the the width and height of the map to be something more like 10 meters. This is a really easy way to get things up and running if you want to tune navigation independent of localization performance. 

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
